config/routes.rb
# frozen_string_literal: true

DmSubscriptions::Engine.routes.draw do
  scope ':locale' do
    namespace :admin do
      scope 'sub' do
        get   '/subscription_plans/financials',          controller: :subscription_plans, action: :financials
        patch '/subscription_plans/sort',                controller: :subscription_plans, action: :sort, as: :subscription_plan_sort
        resources :subscription_plans do
          resources :subscriptions do
            member do
              match 'make_payment', action: 'make_payment', as: 'make_payment', via: %i[get post patch]
            end
          end
        end
      end
    end
    get   '/signup_plan/:plan',                 controller: :subscriptions, action: :signup_plan, as: :signup_plan
    post  '/create_subscription_plan',          controller: :subscriptions, action: :create_subscription_plan, as: :create_subscription_plan
  end
end

app/models/subscription.rb
# frozen_string_literal: true

# paid_until was added to indicate that a subscription is paid up until
# a certain date.  This is particularly important when downgrading a paid plan
# to a lesser plan (free or shorter payment period) - user should have full access
# until the paid period expires - no refunds are offered.
#------------------------------------------------------------------------------
class Subscription < ApplicationRecord
  monetize          :amount_cents, with_model_currency: :amount_currency

  belongs_to        :subscriber, polymorphic: true
  belongs_to        :subscription_plan
  has_many          :subscription_payments
  belongs_to        :discount, class_name: 'SubscriptionDiscount', foreign_key: 'subscription_discount_id'
  belongs_to        :affiliate, class_name: 'SubscriptionAffiliate', foreign_key: 'subscription_affiliate_id'
  belongs_to        :account
  has_one           :billing_address, as: :addressable, class_name: 'Address'

  before_create     :set_renewal_at
  before_update     :apply_discount
  before_destroy    :destroy_gateway_record

  after_save        :set_subscription_role
  after_destroy     :set_subscription_role

  attr_accessor     :creditcard, :address
  attr_reader       :response

  # renewal_period is the number of months to bill at a time
  # default is 1
  validates_numericality_of :renewal_period, only_integer: true, greater_than: 0
  validates_numericality_of :amount, greater_than_or_equal_to: 0
  validate                  :card_storage, on: :create
  validate                  :within_limits, on: :update

  default_scope             { where(account_id: Account.current.id) }
  scope                     :pastdue_renewals, ->(days) { where('next_renewal_at < ? AND paid_until > NULL', days) }
  scope                     :fully_paid, -> { where("state = 'active' AND paid_until > ?", Time.now) }
  scope                     :lapsed, -> { where('paid_until <= ?', Time.now) }
  scope                     :never_paid, -> { where('paid_until IS NULL') }

  # Changes the subscription plan, and assigns various properties,
  # such as limits, etc., to the subscription from the assigned
  # plan.
  #
  # When adding new limits that are specified in SubscriptionPlan,
  # if you name them like "some_quantity_limit", they will automatically
  # be used by this method.
  #
  # Otherwise, you'll need to manually add the assignment to this method.
  #
  # Allow even free accounts to have a trial period (for tasting the full version)
  #------------------------------------------------------------------------------
  def plan=(plan)
    if plan.amount.positive?
      # Discount the plan with the existing discount (if any)
      # if the plan doesn't already have a better discount
      plan.discount = discount if discount && discount > plan.discount

      # If the assigned plan has a better discount, though, then
      # assign the discount to the subscription so it will stick
      # through future plan changes
      self.discount = plan.discount if plan.discount && plan.discount > discount

      # if going from free -> paid, not a trial, and no outstanding paid amount,
      # then set  next_renewal_at to now so that billing can start
      if amount.zero? && !trial? && !currently_paid?
        self.next_renewal_at = Time.now
      end
    else
      # make sure an initial free plan with no trial period is immediately active
      # self.state = 'active' if new_record? && plan.trial_period == 0
    end
    self.state = 'active' if new_record? && plan.trial_period == 0
    self.plan_changed_on = Time.now

    #
    # Find any attributes that exist in both the Subscription and SubscriptionPlan
    # and that match the pattern of "something_limit"
    #
    limits = attributes.keys.select { |k| k =~ /^.+_limit$/ } &
             plan.attributes.keys.select { |k| k =~ /^.+_limit$/ }

    (limits + %i[amount renewal_period]).each do |f|
      send("#{f}=", plan.send(f))
    end

    self.subscription_plan = plan
  end

  # The plan_id and plan_id= methods are convenience methods for the
  # administration interface.
  #------------------------------------------------------------------------------
  def plan_id
    subscription_plan_id
  end

  #------------------------------------------------------------------------------
  def plan_id=(a_plan_id)
    if a_plan_id.to_i != subscription_plan_id
      self.plan = SubscriptionPlan.find(a_plan_id)
    end
  end

  #------------------------------------------------------------------------------
  def inactive?
    state == 'inactive'
  end

  #------------------------------------------------------------------------------
  def active?
    state == 'active'
  end

  #------------------------------------------------------------------------------
  def trial?
    state == 'trial'
  end

  #------------------------------------------------------------------------------
  def trial_days
    (next_renewal_at.to_i - Time.now.to_i) / 86_400
  end

  #------------------------------------------------------------------------------
  def store_card(creditcard, gw_options = {})
    @response = if billing_id.blank?
                  payment_api.gateway.store(creditcard, gw_options)
                else
                  payment_api.gateway.update(billing_id, creditcard, gw_options)
    end

    if @response.success?
      if creditcard.is_a? String
        extracted_card        = payment_api.extract_card(response)
        self.card_number      = extracted_card[:display_number]
        self.card_expiration  = extracted_card[:expiration]
      else
        self.card_number      = creditcard.display_number
        self.card_expiration  = format('%02d-%d', creditcard.expiry_date.month, creditcard.expiry_date.year)
      end
      set_billing
    else
      errors.add(:base, @response.message)
      false
    end
  end

  #------------------------------------------------------------------------------
  def payment_description(start_date = nil)
    date = if start_date
             start_date
           else
             next_renewal_at.present? ? next_renewal_at : Time.now
    end

    I18n.t('subscriptions.invoice_description', plan_name: subscription_plan.name_en, from_date: (date + 1.day).to_date.to_s(:long), to_date: date.advance(months: renewal_period).to_date.to_s(:long))
  end

  # Charge the card on file the amount stored for the subscription
  # record.  This is called by the daily_mailer script for each
  # subscription that is due to be charged.  A SubscriptionPayment
  # record is created, and the subscription's next renewal date is
  # set forward when the charge is successful.
  #------------------------------------------------------------------------------
  def charge
    description = payment_description
    if amount.zero? || (@response = payment_api.gateway.purchase(amount.cents, billing_id, currency: amount.currency, order_id: description)).success?
      unless amount.zero?
        update_attribute(:paid_until, next_renewal_at.advance(months: renewal_period))
      end
      activate_subscription
      unless amount.zero?
        subscription_payments.create(subscriber: subscriber,
                                     amount: amount,
                                     transaction_id: @response.authorization,
                                     payment_processor: payment_api.processor,
                                     description: description,
                                     card_number: card_number)
      end
      true
    else
      errors.add(:base, @response.message)
      false
    end
  end

  # This is for making a manual subscription payment (like if it came in via wire
  # transfer or something, and we just need to record it and send the invoice)
  # no matter the amount, this assumes that the subscription is renewed for the
  # full renewal period
  #------------------------------------------------------------------------------
  def manual_payment(manual_amount = amount)
    description = payment_description
    unless manual_amount.zero?
      update_attribute(:paid_until, next_renewal_at.advance(months: renewal_period))
    end
    activate_subscription
    unless manual_amount.zero?
      subscription_payments.create(subscriber: subscriber,
                                   amount: manual_amount,
                                   transaction_id: nil,
                                   payment_processor: 'manual',
                                   description: description)
    end
    true
  end

  # Charge the card on file any amount you want.  Pass in a dollar
  # amount (1.00 to charge $1).  A SubscriptionPayment record will
  # be created, but the subscription itself is not modified.
  #------------------------------------------------------------------------------
  def misc_charge(amount)
    if amount.zero? || (@response = payment_api.gateway.purchase(amount.cents, billing_id, currency: amount.currency)).success?
      subscription_payments.create(subscriber: subscriber,
                                   amount: amount,
                                   transaction_id: @response.authorization,
                                   payment_processor: payment_api.processor,
                                   card_number: card_number,
                                   misc: true)
      true
    else
      errors.add(:base, @response.message)
      false
    end
  end

  #------------------------------------------------------------------------------
  def needs_payment_info?
    card_number.blank? && subscription_plan.amount.positive?
  end

  # Activate the subscription
  #------------------------------------------------------------------------------
  def activate_subscription
    update_attributes(next_renewal_at: next_renewal_at.advance(months: renewal_period), state: 'active')
  end

  #------------------------------------------------------------------------------

app/controllers/dm_subscriptions/admin/subscriptions_controller.rb
# frozen_string_literal: true

class DmSubscriptions::Admin::SubscriptionsController < DmSubscriptions::Admin::AdminController
  include DmSubscriptions::PermittedParams

  before_action   :plan_lookup
  before_action   :subscription_lookup, except: %i[new create]

  #------------------------------------------------------------------------------
  def new
    @subscription = @subscription_plan.subscriptions.build
  end

  #------------------------------------------------------------------------------
  def edit; end

  #------------------------------------------------------------------------------
  def create
    @subscription = @subscription_plan.subscriptions.new(subscription_params)
    @subscription.subscriber = current_user
    if @subscription.save
      redirect_to admin_subscription_plan_path(@subscription_plan), notice: 'Subscription was successfully created.'
    else
      render action: :new
    end
  end

  #------------------------------------------------------------------------------
  def update
    if @subscription.update_attributes(subscription_params)
      redirect_to admin_subscription_plan_path(@subscription_plan), notice: 'Subscription was successfully updated.'
    else
      render action: :edit
    end
  end

  # [todo]
  #------------------------------------------------------------------------------
  def destroy
    # @forum.destroy
    # redirect_to admin_forum_category_url(@forum.forum_category)
  end

  #------------------------------------------------------------------------------
  def make_payment
    if put_or_post?
      @subscription.billing_address.present? ? @subscription.billing_address.update_attributes(make_payment_billing_address_params) : @subscription.create_billing_address(make_payment_billing_address_params)
      @subscription.update_attribute(:name_on_card, params[:make_payment][:name_on_card])
      amount = Monetize.parse(params[:make_payment][:amount], @subscription.amount.currency)
      if @subscription.manual_payment(amount)
        redirect_to admin_subscription_plan_path(@subscription_plan), notice: 'Payment made'
      end
    else
      @subscription.build_billing_address if @subscription.billing_address.nil?
    end
  end

  private

  #------------------------------------------------------------------------------
  def plan_lookup
    @subscription_plan = SubscriptionPlan.friendly.find(params[:subscription_plan_id])
  end

  #------------------------------------------------------------------------------
  def subscription_lookup
    @subscription = @subscription_plan.subscriptions.find(params[:id])
  end
end

app/controllers/dm_subscriptions/concerns/subscriptions_controller.rb
# frozen_string_literal: true

module DmSubscriptions
  module Concerns
    module SubscriptionsController
      extend ActiveSupport::Concern

      protected

      #------------------------------------------------------------------------------
      def store_billing
        #--- used for customer/client in Stripe/Paymill
        email               = current_user.email
        description         = current_user.full_name
        @address.first_name = @creditcard.first_name
        @address.last_name  = @creditcard.last_name

        #--- store the billing address in subscription
        unless @subscription.billing_address.present?
          @subscription.create_billing_address
        end
        @subscription.update_attributes(name_on_card: "#{@address.first_name} #{@address.last_name}")
        @subscription.billing_address.update_attributes(line1: @address.address1, line2: @address.address2,
                                                        city: @address.city, state: @address.state,
                                                        zip: @address.zip, country_code: @address.country)

        result = if params[:card_token].present?
                   @subscription.store_card(params[:card_token], email: email, description: description)
                 else
                   (@creditcard.valid? & @address.valid?) && @subscription.store_card(@creditcard, email: email, description: description, billing_address: @address.to_activemerchant, ip: request.remote_ip)
        end
        if result
        end
        result
      end

      #------------------------------------------------------------------------------
      def load_billing
        @creditcard = ActiveMerchant::Billing::CreditCard.new(params[:creditcard] || {})
        @address    = SubscriptionAddress.new(params[:address])
      end

      #------------------------------------------------------------------------------
      def load_subscription
        @subscription = current_user.subscription if current_user
      end

      module ClassMethods
      end
    end
  end
end

app/views/dm_subscriptions/admin/subscriptions/_form.html.erb
<% submit_url = (@subscription.new_record? ? admin_subscription_plan_subscriptions_path : admin_subscription_plan_subscription_path) %>
<%= simple_form_for @subscription, url: submit_url,
      html: { class: 'form-horizontal' }, wrapper: :bs3_horizontal_form, wrapper_mappings: DmAdmin::FormWrapperMappings do |f| %>

  <%= f.error_notification message: "Please review the problems below" %>

  <%= panel header: false do %>
    <%= f.input :amount, label: 'Amount', wrapper: :bs3_horizontal_group do %>
      <%= content_tag :span, @subscription.amount.symbol, class: "input-group-addon" %>
      <div class="width_25_percent">
        <%= f.input_field :amount, class: 'form-control' %>
      </div>
    <% end %>
    <%= f.input :next_renewal_at, as: :date_picker, label: 'Next Renewal', input_wrapper_html: {class: 'col-sm-4'}, hint: 'Date when the next subscription charge / renewal will be' %>
    <%= f.input :paid_until, as: :date_picker, label: 'Paid Until', input_wrapper_html: {class: 'col-sm-4'}, hint: 'Subscription is paid up until this date' %>
    <%= f.input :card_number, label: 'Card Number', input_html: {class: 'width_50_percent'} %>
    <%= f.input :card_expiration, label: 'Card Expiration', input_html: {class: 'width_50_percent'} %>
    <%= f.input :state, label: 'Status', required: true, collection: ['active', 'inactive', 'trial'], input_html: {class: 'width_25_percent'} %>
    <%= f.input :billing_id, label: 'Billing ID', disabled: true, input_html: {class: 'width_50_percent'} %>
    <%= submit_or_cancel cancel_url: (@subscription.new_record? ? admin_subscription_plans_path : admin_subscription_plan_path(@subscription_plan)) %>

  <% end %>

<% end %>

app/views/dm_subscriptions/admin/subscriptions/edit.html.erb
<% content_for :content_title, "#{@subscription.subscriber.name} <small>#{@subscription_plan.name}</small>".html_safe %>

<% content_for :content_title_extra do %>
  <%= page_header_buttons do %>
    <%#= present(@workshop).label_published %>
    <%= link_to('Make Payment', make_payment_admin_subscription_plan_subscription_path(@subscription_plan, @subscription), title: 'Make Payment', class: "btn btn-sm btn-default") %>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/dm_subscriptions/admin/subscriptions/make_payment.html.erb
<% submit_url = make_payment_admin_subscription_plan_subscription_path(@subscription_plan, @subscription) %>
<%= simple_form_for :make_payment, url: submit_url,
      html: { class: 'form-horizontal' }, wrapper: :bs3_horizontal_form, wrapper_mappings: DmAdmin::FormWrapperMappings do |f| %>

  <%= f.error_notification message: "Please review the problems below" %>

  <%= panel header: false do %>
    <p>Making a payment <strong>will</strong> renew the subscription date by the plan's renewal period. (monthly, yearly, etc)</p>
    <%= f.input :amount, label: 'Amount', wrapper: :bs3_horizontal_group do %>
      <%= content_tag :span, @subscription.amount.symbol, class: "input-group-addon" %>
      <div class="width_25_percent">
        <%= f.input_field :amount, class: 'form-control', value: @subscription.amount %>
      </div>
    <% end %>
    <% if false %>
      <%= f.input :payment_date, label: 'Paid On', as: :date_picker, input_wrapper_html: {class: 'col-sm-4'} %>
      <%= f.input :payment_method, label: 'Method', as: 'select', collection: WorkshopPrice::PAYMENT_METHODS, include_blank: false, input_html: {style: "width: 200px"} %>
    <% end %>


    <%= subsection title: 'Billing Address (will appear on invoice)' do %>
      <%= f.input :name_on_card, label: 'Name', input_html: {value: @subscription.name_on_card} %>

      <%= f.fields_for :billing_address, @subscription.billing_address, wrapper: :bs3_horizontal_form do |builder| %>
        <%= builder.input :line1, label: I18n.t('core.profile_address') %>
        <%= builder.input :line2, label: ' ' %>
        <%= builder.input :city, label: I18n.t('core.profile_city') %>
        <%= builder.input :state, label: I18n.t('core.profile_state') %>
        <%= builder.input :zip, label: I18n.t('core.profile_zipcode') %>
        <%= builder.input :country, label: I18n.t('core.profile_country') do %>
          <%= ut_country_select_tag('make_payment[billing_address][country_code]', @subscription.billing_address.country_code, as: :code) %>
        <% end %>
      <% end %>

    <% end %>

    <%= submit_or_cancel cancel_url: edit_admin_subscription_plan_subscription_path(@subscription_plan, @subscription) %>

  <% end %>

<% end %>

app/views/dm_subscriptions/admin/subscriptions/new.html.erb
<% content_for :content_title, 'New Subscription' %>
<%= render 'form' %>