config/routes.rb
# frozen_string_literal: true

DmSubscriptions::Engine.routes.draw do
  scope ':locale' do
    namespace :admin do
      scope 'sub' do
        get   '/subscription_plans/financials',          controller: :subscription_plans, action: :financials
        patch '/subscription_plans/sort',                controller: :subscription_plans, action: :sort, as: :subscription_plan_sort
        resources :subscription_plans do
          resources :subscriptions do
            member do
              match 'make_payment', action: 'make_payment', as: 'make_payment', via: %i[get post patch]
            end
          end
        end
      end
    end
    get   '/signup_plan/:plan',                 controller: :subscriptions, action: :signup_plan, as: :signup_plan
    post  '/create_subscription_plan',          controller: :subscriptions, action: :create_subscription_plan, as: :create_subscription_plan
  end
end

app/models/subscription_plan.rb
# frozen_string_literal: true

class SubscriptionPlan < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  has_many                  :subscriptions

  monetize                  :price_cents, with_model_currency: :price_currency
  monetize                  :setup_price_cents, with_model_currency: :price_currency

  # --- globalize
  translates                :name, fallbacks_for_empty_translations: true
  globalize_accessors       locales: DmCore::Language.language_array

  # --- FriendlyId
  extend FriendlyId
  include DmCore::Concerns::FriendlyId

  include RankedModel
  ranks                     :row_order, with_same: :account_id

  # renewal_period is the number of months to bill at a time
  # default is 1
  validates_numericality_of :renewal_period, only_integer: true, greater_than: 0
  validates_numericality_of :trial_period, only_integer: true, greater_than_or_equal_to: 0
  validates_inclusion_of    :trial_interval, in: %w[months days]
  validate                  :require_name

  attr_accessor             :discount

  default_scope             { where(account_id: Account.current.id) }

  # for now, always force it to the preferred_default_currency
  #------------------------------------------------------------------------------
  def price_currency
    Account.current.preferred_default_currency
  end

  #------------------------------------------------------------------------------
  def require_name
    if send("name_#{Account.current.preferred_default_locale}").blank?
      errors.add "name_#{Account.current.preferred_default_locale}", I18n.t('errors.messages.blank')
    end
  end

  #------------------------------------------------------------------------------
  def to_s
    "#{name} - #{amount.format} / month"
  end

  #------------------------------------------------------------------------------
  def amount(include_discount = true)
    include_discount && @discount && @discount.apply_to_recurring? ? price - @discount.calculate(price) : price
  end

  #------------------------------------------------------------------------------
  def setup_amount(include_discount = true)
    include_discount && setup_price.present? && @discount && @discount.apply_to_setup? ? setup_price - @discount.calculate(setup_price) : setup_price
  end

  #------------------------------------------------------------------------------
  def trial_period(include_discount = true)
    include_discount && @discount ? self[:trial_period] + @discount.trial_period_extension : self[:trial_period]
  end

  #------------------------------------------------------------------------------
  def revenues
    @revenues ||= subscriptions.group('subscriptions.state').calculate(:sum, :price)
  end
end

app/controllers/dm_subscriptions/admin/subscription_plans_controller.rb
# frozen_string_literal: true

class DmSubscriptions::Admin::SubscriptionPlansController < DmSubscriptions::Admin::AdminController
  include DmSubscriptions::PermittedParams

  before_action :plan_lookup, except: %i[index new create financials]

  #------------------------------------------------------------------------------
  def index
    @subscription_plans = SubscriptionPlan.rank(:row_order)
    @upccoming_renewals = Subscription.where('amount_cents > 0 AND next_renewal_at >= ? AND next_renewal_at < ?', Time.now - 6.days, Time.now + 2.weeks).order('next_renewal_at ASC')
    @pastdue_renewals   = Subscription.pastdue_renewals(Time.now - 6.days).order('next_renewal_at DESC')
    @updated_plans      = Subscription.where('plan_changed_on > ?', Time.now - 7.days).order('plan_changed_on DESC')
  end

  #------------------------------------------------------------------------------
  def new
    @subscription_plan = SubscriptionPlan.new
  end

  #------------------------------------------------------------------------------
  def edit; end

  #------------------------------------------------------------------------------
  def create
    @subscription_plan = SubscriptionPlan.new(subscription_plan_params)
    if @subscription_plan.save
      redirect_to admin_subscription_plan_path(@subscription_plan), notice: 'Subscription Plan was successfully created.'
    else
      render action: :new
    end
  end

  #------------------------------------------------------------------------------
  def update
    if @subscription_plan.update_attributes(subscription_plan_params)
      redirect_to admin_subscription_plan_path(@subscription_plan), notice: 'Subscription Plan was successfully updated.'
    else
      render action: :edit
    end
  end

  #------------------------------------------------------------------------------
  def financials; end

  #------------------------------------------------------------------------------
  def show
    @fully_paid = @subscription_plan.subscriptions.fully_paid
    @lapsed     = @subscription_plan.subscriptions.lapsed
    @never_paid = @subscription_plan.subscriptions.never_paid
  end

  #------------------------------------------------------------------------------
  def sort
    @subscription_plan.update_attribute(:row_order_position, params[:item][:row_order_position])

    #--- this action will be called via ajax
    head :ok
  end

  private

  #------------------------------------------------------------------------------
  def plan_lookup
    @subscription_plan = SubscriptionPlan.friendly.find(params[:id])
  end
end

app/views/dm_subscriptions/admin/subscription_plans/_form.html.erb
<% submit_url = (@subscription_plan.new_record? ? admin_subscription_plans_path : admin_subscription_plan_path) %>
<%= simple_form_for @subscription_plan, url: submit_url,
      html: { class: 'form-horizontal' }, wrapper: :bs3_horizontal_form, wrapper_mappings: DmAdmin::FormWrapperMappings do |f| %>

  <%= f.error_notification message: "Please review the problems below" %>
  <%= panel header: false do %>

    <%= locale_tabs do |locale| %>
      <%= f.input "name_#{locale}", label: 'Plan Name', required: true %>
    <% end %>

    <%= f.input :slug, label: 'Slug', hint: 'Short name for this plan', required: true %>
    <%= f.input :price, label: 'Amount', wrapper: :bs3_horizontal_group do %>
      <%= content_tag :span, @subscription_plan.price.symbol, class: "input-group-addon" %>
      <div class="width_25_percent">
        <%= f.input_field :price, class: 'form-control' %>
      </div>
    <% end %>
    <%= f.input :renewal_period, label: 'Renewal Period', input_html: {class: 'width_25_percent'}, required: true %>
    <%= f.input :setup_price, label: 'Setup Amount', wrapper: :bs3_horizontal_group do %>
      <%= content_tag :span, @subscription_plan.price.symbol, class: "input-group-addon" %>
      <div class="width_25_percent">
        <%= f.input_field :setup_price, class: 'form-control' %>
      </div>
    <% end %>
    <%= f.input :trial_period, label: 'Trial Period', input_html: {class: 'width_25_percent'}, required: true %>
    <%= f.input :trial_interval, label: 'Trial Interval', input_html: {class: 'width_25_percent'}, required: true, collection: ['months', 'days'] %>

    <%= submit_or_cancel cancel_url: (@subscription_plan.new_record? ? admin_subscription_plans_path : admin_subscription_plan_path(@subscription_plan)) %>
  <% end %>


<% end %>

app/views/dm_subscriptions/admin/subscription_plans/edit.html.erb
<% content_for :content_title, "#{@subscription_plan.name}".html_safe %>
<%= render 'form' %>

app/views/dm_subscriptions/admin/subscription_plans/financials.html.erb
<% content_for :content_title, "Subscription Financial Details" %>

<% if false %>
<div class="row">
  <div class="col-md-12">
    <%= panel title: 'Summary' do %>
      <div class="chart span6" style="height: 185px;margin-bottom:20px;" id="payment_outstanding_chart"
           data-values="<%= [ {label: "Paid: #{@financials[:summary][:total_paid].format(no_cents_if_whole: true, symbol: true)}",
                               data: @financials[:summary][:total_paid].to_f, color: '#4DB24A' },
                              {label: "Outstanding: #{@financials[:summary][:total_outstanding].format(no_cents_if_whole: true, symbol: true)}",
                               data: @financials[:summary][:total_outstanding].to_f, color: '#F24E50' }
                            ].to_json %>">
      </div>

      <div class="span6">
        <table class="table table-bordered table-condensed" style="margin-top:10px">
          <thead>
            <tr>
              <th class="name"></th>
              <th class="cost">Best</th>
              <th class="cost">Worst <small>(80%)</small></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><strong>Projected Revenue</strong></th>
              <td class="cost"><%= @financials[:summary][:total_possible].format(no_cents_if_whole: true, symbol: true) %></td>
              <td class="cost"><%= @financials[:summary][:total_possible_worst].format(no_cents_if_whole: true, symbol: true) %></td>
            </tr>
            <tr>
              <th><strong>Outstanding</strong></th>
              <td class="cost"><%= @financials[:summary][:total_outstanding].format(no_cents_if_whole: true, symbol: true) %></td>
              <td class="cost"><%= @financials[:summary][:total_outstanding_worst].format(no_cents_if_whole: true, symbol: true) %></td>
            </tr>
            <tr>
              <th><strong>Paid</strong></th>
              <td colspan="2" class="cost"><%= @financials[:summary][:total_paid].format(no_cents_if_whole: true, symbol: true) %></td>
            </tr>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <%= panel title: 'Collected Payments by Month' do %>
      <div class="span7 chart" style="height: 200px" id="collected_monthly_chart"
           data-values="<%= financial_collected_monthly_json(@financials[:collected_monthly]) %>"
           data-currencysymbol="<%= Money.new(0, @workshop.base_currency).symbol %>" >
      </div>
      <div class="span5">
        <table class="table table-bordered table-condensed" style="margin-top:10px">
          <tbody>
            <% @financials[:collected_monthly].sort.each_with_index do |item, index| -%>
              <tr>
                <td class="name"><%= item[0].localize("%b %Y") %></td>
                <td class="cost" style="text-align: right;"><%= @financials[:collected_monthly][item[0]].format(no_cents_if_whole: true, symbol: true) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <%= panel title: 'Collected Payments by Method' do %>
      <div class="chart" style="height: 185px;" id="collected_chart" data-values="<%= financial_collected_json(@financials[:collected]) %>">
      </div>
    <% end %>
  </div>
</div>
<% end %>

<% if false %>
<%= panel title: 'List of Payments' do %>
  <table class="table table-bordered table-condensed table-striped">
    <thead>
      <tr>
        <th class="date">Date</th>
        <th class="name">Name</th>
        <th class="item_id">Item ID / Description</th>
        <th class="cost">Paid</th>
        <th class="payment_method">Payment Method</th>
        <th class="type">Recorded By</th>
      </tr>
    </thead>
    <tbody>
      <% @payments.sort { |x, y| x.payment_date <=> y.payment_date }.each_with_index do |payment, index| -%>
        <tr>
          <td class="date" style="white-space:nowrap"><%= format_date(payment.payment_date) %></td>
          <td class="name"><%= payment.owner.full_name %></td>
          <td class="item_id"><%= payment.item_ref %></td>
          <td class="cost"><%= payment.total.format(no_cents_if_whole: true, symbol: true) %></td>
          <td class="payment_method" style="white-space:nowrap"><%= payment.payment_method.titleize %></td>
          <td class="type"><%= payment.user_profile.nil? ? 'Automated' : payment.user_profile.public_name %></td>
        </tr>
        <% if !payment.bill_to_name.blank? || payment.discount.to_i > 0 || (!payment.order_details.nil? && !payment.order_details['coupon'].nil?) %>
          <tr>
            <td></td>
            <td colspan="5">
              <ul class="row_detail">
                <% unless payment.bill_to_name.blank? %>
                  <li><strong>Payed by:</strong> <%=h payment.bill_to_name %></li>
                <% end %>
                <% if payment.discount.to_i > 0 %>
                  <li><strong>Discount:</strong> <%=h payment.discount %></li>
                <% end %>
                <% unless payment.order_details.nil? || payment.order_details['coupon'].nil? %>
                  <li><strong>Coupon Code:</strong> <%=h payment.order_details['coupon']['coupon_code'] %></li>
                <% end %>
              </ul>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>
<% end %>

app/views/dm_subscriptions/admin/subscription_plans/index.html.erb
<% payment_stats = SubscriptionPayment.stats %>
<% content_for :content_title, 'Subscription Plans' %>
<% content_for :content_title_extra do %>
  <%= page_header_buttons do %>
    <div class="header-bar-stats">
      <ul class="statistics statistics-small">
          <li><%= stat_block_small label: 'Revenue (last month)', number: humanized_money_with_symbol(payment_stats[:last_month]),
                      percent: 100, color_type: :warning, icon: ::CommonIcons[:money], url: '#' %></li>
          <li><%= stat_block_small label: 'Revenue (this month)', number: humanized_money_with_symbol(payment_stats[:this_month]),
                      percent: 100, color_type: :success, icon: ::CommonIcons[:money], url: '#' %></li>
          <li><%= stat_block_small label: 'Paying Subscribers', number: ::User.paid_subscribers.count,
                      percent: 100, color_type: :info, icon: ::CommonIcons[:user], url: '#' %></li>
      </ul>
    </div>
  <% end %>
  <div class="header-statistics">
    <div class="collapse" id="header-bar-stats">
      <div class="well">
        <ul class="statistics">
          <li><%= stat_block_small label: 'Revenue (last month)', number: humanized_money_with_symbol(payment_stats[:last_month]),
                      percent: 100, color_type: :warning, icon: 'icon-coin', url: '#' %></li>
          <li><%= stat_block_small label: 'Revenue (this month)', number: humanized_money_with_symbol(payment_stats[:this_month]),
                      percent: 100, color_type: :success, icon: 'icon-coin', url: '#' %></li>
          <li><%= stat_block_small label: 'Paying Subscribers', number: ::User.paid_subscribers.count,
                      percent: 100, color_type: :info, icon: 'icon-user', url: '#' %></li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<% toolbar = toolbar_btn(icons(:new), new_admin_subscription_plan_path, title: 'New Subscription Plan', class: "btn btn-xs btn-default") %>
<%= panel body: false, title: 'Plans', toolbar: toolbar do %>
  <table id="drag_sort" class="table table-striped table-bordered table-block" data-update_url="<%= dm_subscriptions.admin_subscription_plan_sort_path %>">
    <thead>
      <tr>
        <th class="sort_handle"></th>
        <th>Plan Name</th>
        <th>Amount</th>
        <th>Renewal Period</th>
        <th>Paying / Total</th>
        <th>Estimated Revenue</th>
      </tr>
    </thead>
    <tbody>
      <% @subscription_plans.each do |plan| %>
        <tr class="item" data-item_id="<%= plan.id %>">
          <td class="sort_handle"></td>
          <td><%= link_to plan.name, [:admin, plan] %></td>
          <td><%= humanized_money_with_symbol plan.amount %></td>
          <td><%= plan.renewal_period %> / <%= 'month'.pluralize(plan.renewal_period) %></td>
          <td><%= plan.amount.positive? ? plan.subscriptions.fully_paid.count : '0' %> / <%= plan.subscriptions.count %></td>
          <td><%= humanized_money_with_symbol(plan.amount * plan.subscriptions.fully_paid.count / plan.renewal_period) %> / Month</td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div class="row">
  <div class="col-md-6">
    <%= panel body: false, title: "New/Changed <small>previous 7 days</small>".html_safe do %>
      <table class="table table-bordered table-condensed table-striped">
        <thead>
          <tr>
            <th class="name">Name</th>
            <th class="cost">Balance</th>
            <th class="date">Renewal</th>
          </tr>
        </thead>
        <tbody>
          <% @updated_plans.each do |subscription| -%>
            <tr>
              <td class="name"><%= subscription.subscriber.full_name %></td>
              <td class="cost"><%= subscription.amount.format %></td>
              <td class="date" style="white-space:nowrap">
                <%= subscription.current? ? format_date(subscription.next_renewal_at) : colored_label(format_date(subscription.next_renewal_at), :warning) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= panel body: false, title: "Upcoming Paid Renewals <small>next 2 weeks</small>".html_safe do %>
      <table class="table table-bordered table-condensed table-striped">
        <thead>
          <tr>
            <th class="name">Name</th>
            <th class="cost">Balance</th>
            <th class="date">Renewal</th>
          </tr>
        </thead>
        <tbody>
          <% @upccoming_renewals.each do |subscription| -%>
            <tr>
              <td class="name"><%= subscription.subscriber.full_name %></td>
              <td class="cost"><%= subscription.amount.format %></td>
              <td class="date" style="white-space:nowrap">
                <%= subscription.current? ? format_date(subscription.next_renewal_at) : colored_label(format_date(subscription.next_renewal_at), :warning) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <%= panel body: false, title: "Past Due Renewals" do %>
      <table class="table table-bordered table-condensed table-striped">
        <thead>
          <tr>
            <th class="name">Name</th>
            <th class="cost">Balance</th>
            <th class="date">Renewal</th>
          </tr>
        </thead>
        <tbody>
          <% @pastdue_renewals.each do |subscription| -%>
            <tr>
              <td class="name"><%= subscription.subscriber.full_name %></td>
              <td class="cost"><%= subscription.amount.format %></td>
              <td class="date" style="white-space:nowrap">
                <%= colored_label(format_date(subscription.next_renewal_at), :warning) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/dm_subscriptions/admin/subscription_plans/new.html.erb
<% content_for :content_title, 'New Subscription Plan' %>
<%= render 'form' %>

app/views/dm_subscriptions/admin/subscription_plans/show.html.erb
<% content_for :content_title, "#{@subscription_plan.name} (#{humanized_money_with_symbol @subscription_plan.amount}) <small>Subscription Plan</small>".html_safe %>
<% content_for :content_title_extra do %>
  <%= page_header_buttons do %>
    <%= link_to(icon_label(:edit, 'Edit'), edit_admin_subscription_plan_path(@subscription_plan), title: 'Edit Subscription Plan', class: "btn btn-sm btn-default") %>
  <% end %>
<% end %>

<% toolbar = toolbar_btn(icons(:new), new_admin_subscription_plan_subscription_path(@subscription_plan), title: 'New Subscription', class: "btn btn-xs btn-default") %>
<%= panel body: false, title: "Fully Paid", toolbar: toolbar do %>
  <table class="table table-striped table-bordered table-block">
    <thead>
      <tr>
        <th>Subscriber</th>
        <th>State</th>
        <th>Amount</th>
        <th>Next Renewal At</th>
        <th>Paid Until</th>
        <th>Card Number</th>
        <th>Billing ID</th>
      </tr>
    </thead>
    <tbody>
      <% @fully_paid.each do |subscription| %>
        <tr class="item">
          <td><%= link_to "#{subscription.subscriber.name}", edit_admin_subscription_plan_subscription_path(@subscription_plan, subscription) %></td>
          <td><%= subscription.state %></td>
          <td><%= humanized_money_with_symbol subscription.amount %></td>
          <td><%= format_date(subscription.next_renewal_at) %></td>
          <td><%= format_date(subscription.paid_until) %></td>
          <td><%= subscription.card_number %></td>
          <td><%= subscription.billing_id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= panel body: false, title: "Lapsed Subscriptions" do %>
  <table class="table table-striped table-bordered table-block">
    <thead>
      <tr>
        <th>Subscriber</th>
        <th>State</th>
        <th>Amount</th>
        <th>Next Renewal At</th>
        <th>Paid Until</th>
        <th>Card Number</th>
        <th>Billing ID</th>
      </tr>
    </thead>
    <tbody>
      <% @lapsed.each do |subscription| %>
        <tr class="item">
          <td><%= link_to "#{subscription.subscriber.name}", edit_admin_subscription_plan_subscription_path(@subscription_plan, subscription) %></td>
          <td><%= subscription.state %></td>
          <td><%= humanized_money_with_symbol subscription.amount %></td>
          <td><%= format_date(subscription.next_renewal_at) %></td>
          <td><%= format_date(subscription.paid_until) %></td>
          <td><%= subscription.card_number %></td>
          <td><%= subscription.billing_id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= panel body: false, title: "Never Paid" do %>
  <table class="table table-striped table-bordered table-block">
    <thead>
      <tr>
        <th>Subscriber</th>
        <th>State</th>
        <th>Amount</th>
        <th>Next Renewal At</th>
        <th>Paid Until</th>
        <th>Card Number</th>
        <th>Billing ID</th>
      </tr>
    </thead>
    <tbody>
      <% @never_paid.each do |subscription| %>
        <tr class="item">
          <td><%= link_to "#{subscription.subscriber.name}", edit_admin_subscription_plan_subscription_path(@subscription_plan, subscription) %></td>
          <td><%= subscription.state %></td>
          <td><%= humanized_money_with_symbol subscription.amount %></td>
          <td><%= format_date(subscription.next_renewal_at) %></td>
          <td><%= format_date(subscription.paid_until) %></td>
          <td><%= subscription.card_number %></td>
          <td><%= subscription.billing_id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>